/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#424754',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-tint': '#005ac2',
        'primary-container': '#2170e4',
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'on-primary-container': '#fefcff',
        'surface-bright': '#f7f9fb',
        primary: '#0058be',
        'on-tertiary-container': '#fffbff',
        'surface-container-high': '#e6e8ea',
        'on-secondary': '#ffffff',
        'outline-variant': '#c2c6d6',
        tertiary: '#924700',
        'tertiary-container': '#b75b00',
        'on-primary-fixed-variant': '#004395',
        'on-primary-fixed': '#001a42',
        'on-surface': '#191c1e',
        'secondary-container': '#dae2fd',
        surface: '#f7f9fb',
        'on-tertiary-fixed': '#311400',
        secondary: '#565e74',
        'primary-fixed': '#d8e2ff',
        'inverse-on-surface': '#eff1f3',
        'surface-container-low': '#f2f4f6',
        'surface-container-highest': '#e0e3e5',
        background: '#f7f9fb',
        'tertiary-fixed': '#ffdcc6',
        outline: '#727785',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed-variant': '#723600',
        'on-secondary-container': '#5c647a',
        'on-background': '#191c1e',
        'inverse-primary': '#adc6ff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb786',
        'surface-dim': '#d8dadc',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        error: '#ba1a1a',
        'inverse-surface': '#2d3133',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        base: '8px',
        'stack-lg': '80px',
        'margin-desktop': '64px',
        'container-max': '1440px',
        'stack-sm': '12px',
        'stack-md': '32px',
        gutter: '24px',
      },
      fontFamily: {
        'label-sm': ['Geist Mono', 'monospace'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'display-xl-mobile': ['Inter', 'sans-serif'],
        'display-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-xl-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      animation: {
        'bounce-slow': 'bounceSlow 4s ease-in-out infinite',
      },
      keyframes: {
        bounceSlow: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
      },
    },
  },
  plugins: [],
};
